### ISSUE TITLE
[Request] Can you please add bar plots features?

### ISSUE THREAD

**Issue by euisuk-chung** [splunk/splunk-plotly-collection-viz#2]
**Is your feature request related to a problem? Please describe.**

=> **Current library does not contain Bar plot modules.** 

**Describe the solution you'd like**

=> **Need bar plotting module, which includes stacked bar plots, etc.**

**Comment by euisuk-chung** [comment]
I felt that the Bar Plot, which is basically provided by Splunk, has a lot of restrictions on visual expression. I asked if it is possible to implement this function because there are some functional parts that are not working well and the plot is much better visually. (ex. Bar Width Size Control, Font setting, etc.)

REF: https://community.splunk.com/t5/Dashboards-Visualizations/Chart-Bar-Chart-Configuring-Questions-Fonts-and-Formats/m-p/654599#M53841

**Comment by edro15** [comment]
Hi @euisuk-chung , 

If you need more customisations you can always extend the simpleXML code of your dashboard with CSS and JS. You got some examples as replies in the [Splunk Answer](https://community.splunk.com/t5/Dashboards-Visualizations/Chart-Bar-Chart-Configuring-Questions-Fonts-and-Formats/m-p/654599#M53841) you reported. 😉 

Unfortunately the main object of this visualization is not offering "clones" of visualizations already available out-of-the-box by Splunk, but to offer new ones.
