### ISSUE TITLE
Could Not see the Dashboard example - only box plot

### ISSUE THREAD

**Issue by lem0n43** [splunk/splunk-plotly-collection-viz#3]
## Describe the bug
"No matching visualization found for type: boxplot, in app: splunk_plotly_collection_viz"
Error occurs randomly.

## To Reproduce
1. Go to "Apps / Search & Reporting / Dashboards"
2. Click on the dashboard Overview of Plotly Charts for Splunk

##  Screenshots
I cant' upload capture image in this issues page, (I don't know why..)
So to put it in words
I just can't see viz type **"splunk_plotly_collection_viz.boxplot"** randomly. 
(But in most cases it is not visible)
The other viz type work fine.

**The Permission is**
- All apps(system)

**The properties is**
- Update checking : YES
- Visible : NO

**The Dashboard code is this.**
``` 
<row>
<panel>
      <title>Boxplot Chart</title>
      <viz type="splunk_plotly_collection_viz.boxplot">
        <search>
          <query>
            | makeresults count=100
            | streamstats count as group_num
            | eval group_num = ((group_num-1) % 5)+1
            | eval group_num = "Test ".group_num 
            | eval y=random() %51
            | fields - _time
          </query>
          <earliest>-24h@h</earliest>
          <latest>now</latest>
          <sampleRatio>1</sampleRatio>
        </search>
        <option name="drilldown">none</option>
        <option name="trellis.enabled">0</option>
        <option name="trellis.scales.shared">1</option>
        <option name="trellis.size">medium</option>
      </viz>
    </panel>
  </row>
```

##  Desktop (please complete the following information)
 - OS: Window
 - Browser : edge
 - Version  : v2.4.0
 - Splunk Version : 8.2.9

**Comment by edro15** [comment]
Hi @lem0n43 ,

Thanks for reaching out! Unfortunately I cannot reproduce this behaviour. Have you tried using a different browser (e.g. Chrome, Firefox, etc)? 

"No matching visualization found for type: boxplot, in app: splunk_plotly_collection_viz" suggests there may be an issue with your app folder structure. There must be `$SPLUNK_HOME/etc/apps/splunk-plotly-collection-viz/appserver/static/visualizations/boxplot` and you should see a file named `visualization.js` in there. If that's not the case, please re-install the app.

**Comment by lem0n43** [comment]
@edro15 
The problem is my Splunk enviroment.
I  had already downloaded another box plot app.
When I disable the app(already one), I can see the box-plot graph clearly.
Maybe there are some conflict wit these two app, So it can't see the graph.

Thank you for your help!
